version: '2'
volumes:
  zt1v:
services:
  zerotier:
    image: zyclonite/zerotier:router
    container_name: zerotier-one
    restart: always
    environment:
      - ZEROTIER_ONE_GATEWAY_MODE=inbound
      - ZEROTIER_ONE_NETWORK_IDS=[your networkid]
    volumes:
      - zt1v:/var/lib/zerotier-one
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun